services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_notification
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dang972004@
      MYSQL_DATABASE: notification1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservices_network

  eureka-server:
    image: eurekaserver:latest  # Đảm bảo bạn có Docker image cho Eureka Server
    container_name: eureka_server
    ports:
      - "8671:8671"
    networks:
      - microservices_network

  notification-service:
    image: notification-service:latest
    container_name: notification_service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/notification1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8671/eureka
    ports:
      - "8084:8084"
    networks:
      - microservices_network

volumes:
  mysql_data:

networks:
  microservices_network:
    driver: bridge
