spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka
