spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservice-portfolio
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: profile-service

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
