spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://localhost:3306/project
#    url: jdbc:mysql://localhost:3307/project
#    username: user
#    password: password
    username: root
    password: Dang972004@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
