spring:
  application:
    name: image-service

  datasource:
    url: jdbc:mysql://localhost:3309/image
    username: user
    password: password

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka

cloudinary:
  cloud_name: dhv7v0enl
  api_key: 321888329748168
  api_secret: tJYJsxpU4KbSNEjJju49n_06l3c
