services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    restart: always

  profile-service:
    build: .
    container_name: profile-service
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=profile-service
      - SERVER_PORT=8085
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/microservice-portfolio
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8671/eureka
    restart: always

volumes:
  mongodb_data: